title: digital + health = data
subtitle: collection of references, notes, and knowledge

# Author/Organization info to be displayed in the templates
author:
  name: Alice Andalò
  url:

author:
  name: Nicola Gentili
  url:

author:
  name: Martina Cavallucci
  url:

logourl: /assets/img/logo.png
logoalt: DHK